from . import admin
from . import exel_uchun
from . import band_qilish
from . import rek
from . import navbat
from . import bonuc
from . import kon_loc
from . import qabul_inline
from . import qabul_inline_RU
from . import qabul
from . import qabul_RU
from . import til
from . import Eslatma
